const fs = require("fs");
const glob = require("glob-fs")({ gitignore: true });
const files = glob.readdirSync("./src/patterns/**/*.js", {});
const chalk = require("chalk");

let file = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n\n`;

files.forEach(filePath => {

  process.platform.includes("win") ? filePath = filePath.replace(/\\/g,"/") : '';

  if( filePath.indexOf('config') == -1 ){
    filePath = filePath
      .split("/")
      .splice(2, filePath.split("/").length - 2)
      .join("/");
    file += 'export * from "../patterns/' + filePath + '";\n';
  } else {
    console.warn(chalk.yellow(`[ JS Build ] Excluding file ${chalk.bold.green(" " + filePath
      .split("/")
      .pop() + " ")} because it looks to be a fractal config`));
  }
  
});

fs.writeFileSync("src/js/patterns.js", file);
