// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {defineVars as colors} from './colors.json'
import {defineVars as deviceSizes} from './device-sizes.json'
import {defineVars as fontSizes} from './font-sizes.json'
import {defineVars as fontWeights} from './font-weights.json'
import {defineVars as lineHeights} from './line-heights.json'
import {defineVars as spacing} from './spacing.json'
import {defineVars as transitionLengths} from './transition-lengths.json'
import {defineVars as zIndexes} from './z-indexes.json'

export {
	colors,
	deviceSizes,
	fontSizes,
	fontWeights,
	lineHeights,
	spacing,
	transitionLengths,
	zIndexes
};
